# Generated by Django 3.1.1 on 2020-09-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Description',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
