# Generated by Django 3.1.1 on 2020-09-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200911_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
